//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::collection::Entity as Collection;
pub use super::collection_product::Entity as CollectionProduct;
pub use super::config::Entity as Config;
